compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

pnpMode: strict

changesetBaseRefs:
    - main
    - origin/main

defaultSemverRangePrefix: ''

supportedArchitectures:
    os:
        - current
        - darwin
        - linux
        - win32
    cpu:
        - current
        - x64
        - ia32
        - arm64
        - x86
    libc:
        - current
        - glibc
        - musl

yarnPath: .yarn/releases/yarn-4.0.2.cjs

enableTelemetry: false

nmSelfReferences: false

npmPublishAccess: restricted

npmRegistryServer: 'https://registry.npmjs.org'

progressBarStyle: 'patrick'

# MAKE YARN FAIL ON CERTAIN WARNINGS
logFilters:
    # https://yarnpkg.com/advanced/error-codes#yn0002---missing_peer_dependency
    - code: YN0002
      level: error

    # https://yarnpkg.com/advanced/error-codes#yn0003---cyclic_dependencies
    - code: YN0003
      level: error

      # https://yarnpkg.com/advanced/error-codes#yn0059---invalid_range_peer_dependency
    - code: YN0059
      level: error

      # https://yarnpkg.com/advanced/error-codes#yn0060---incompatible_peer_dependency
    - code: YN0060
      level: error

      # https://yarnpkg.com/advanced/error-codes#yn0061---deprecated_package
    - code: YN0061
      level: error

      # https://yarnpkg.com/advanced/error-codes#yn0002---missing_peer_dependency
    - code: YN0086
      level: error
